global:
  checkNewVersion: true
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

ping: {}

entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"
#tls:
#  certificates:
#    - certFile: /certs/localhost.crt
#      keyFile: /certs/localhost.key

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: public-net
    watch: true

  file:
    directory: "/etc/traefik/dynamic"
    watch: true

log:
  level: INFO
  filePath: "/var/log/traefik/traefik.log"

accessLog:
  filePath: "/var/log/traefik/access.log"

metrics:
  prometheus: {}

certificatesResolvers:
  letsencrypt:
    acme:
      email: mkourany92@mosalam.com
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web
